apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-healthcheck-operator
  namespace: openshift-workload-availability
spec:
  channel: stable
  installPlanApproval: Manual
  name: node-healthcheck-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
