apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nodehealthcheck-worker
spec:
  minHealthy: 51%
  remediationTemplate:
    apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
    kind: FenceAgentsRemediationTemplate
    name: fenceagentsremediationtemplate-worker
    namespace: openshift-workload-availability
  selector:
    matchExpressions:
    - key: node-role.kubernetes.io/virtualization
      operator: Exists
  unhealthyConditions:
  - duration: 300s
    status: "False"
    type: Ready
  - duration: 300s
    status: Unknown
    type: Ready
