apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-core-generator-all
placementBindingDefaults:
  name: cluster-config-binding-all
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: acm-policies
  metadataComplianceType: "musthave"
  complianceType: "mustonlyhave"
  remediationAction: enforce
  severity: medium
  policySets:
    - policyset-all-clusterconfig
  standards:
    - NIST SP 800-53

policies:

####  Cluster Policy Start For All Clusters ####




- name: enable-etcd-encryption
  manifests:
    - path: ./etcd-encrypt/overlays/default



####  Cluster Policy Ends For All Clusters ####





policySets:
  - description: Policy set for the policies which are going to be deployed into all clusters
    name: policyset-all-clusterconfig
    placement:
      placementName: placement-all

