---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: kubevirt-hyperconverged
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  operatorGroup:
    name: openshift-cnv
    targetNamespaces: 
      - openshift-cnv
  upgradeApproval: Automatic
---
