apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldap
    mappingMethod: claim
    type: LDAP

    ldap:
      attributes:
        id:
        - sAMAccountName
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      ca:
        name: ca-config-map
      bindDN: "changeme"
      bindPassword:
        name: ldap-secret
      insecure: false
      url: "changeme"
