enableUserWorkload: true
prometheusK8s:
  retention: 3d
  volumeClaimTemplate:
    metadata:
      name: prometheus-pvc
    spec:
      storageClassName: thin-csi
      resources:
        requests:
          storage: 50Gi
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
grafana:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
k8sPrometheusAdapter:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
kubeStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
telemeterClient:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
openshiftStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
thanosQuerier:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
alertmanagerMain:
  nodeSelector:
    node-role.kubernetes.io/infra-generic: ""
