apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: o
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    name: multicluster-global-hub-operator-rh
    namespace: multicluster-global-hub
    channel: release-1.7
  operatorGroup:
    name: multicluster-global-hub-operator-rh
    targetNamespaces:
      - multicluster-global-hub
  upgradeApproval: Automatic
