apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: public-net
  namespace: openshift-storage
spec:
  config: '{
     "cniVersion": "0.3.1",
     "type": "macvlan", 
     "master": "br-odf", 
     "mode": "bridge",
     "ipam": {
       "type": "whereabouts", 
       "range": "10.99.1.0/24", 
       "routes": [             
         {"dst": "10.99.0.0/24"}
       ]
     }
   }'

