apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  enableCephTools: true
  arbiter: {}
  encryption:
    keyRotation:
      schedule: '@weekly'
    kms: {}
  externalStorage: {}
  flexibleScaling: true
  managedResources:
    cephBlockPools:
      defaultStorageClass: true
      defaultVirtualizationStorageClass: true
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephRBDMirror: {}
    cephToolbox: {}
  monDataDirHostPath: /var/lib/rook
  network:
    connections:
      encryption: {}
    multiClusterService: {}
    provider: multus
    selectors:
      cluster: openshift-storage/public-net
      public: openshift-storage/public-net
  nfs:
    enable: true
  nodeTopologies: {}
  resourceProfile: performance
  storageDeviceSets:
  - config: {}
    count: 36
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset-localblock
    placement: {}
    preparePlacement: {}
    replica: 1
    resources: {}
