apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ocs4registry
  namespace: openshift-image-registry
spec: 
  storageClassName: ocs-storagecluster-cephfs
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 100Gi
  volumeMode: Filesystem

