apiVersion: v1
kind: Namespace
metadata:
  name: openshift-migration
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtc-operator
  namespace: "openshift-migration"
spec:
  channel: "release-v1.7"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "mtc-operator"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration
  namespace: openshift-migration
spec: 
  targetNamespaces: 
    - openshift-migration
  upgradeStrategy: Default
