apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - logging-clf.yaml
patches:
  - path: ./patch-logging-subs.yaml
    target:
      name: cluster-logging
      kind: Subscription
