apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
spec:
  channel: changeme
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
