apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  rules:
    enabled: true
    selector:
      matchLabels:
        openshift.io/cluster-monitoring: "true"
    namespaceSelector:
      matchLabels:
        openshift.io/cluster-monitoring: "true"
  size: 1x.small
  storage:
    tls:
      caName: changeme
    schemas:
    - version: v13
      effectiveDate: "2025-04-09"
    secret:
      name: logging-loki-s3
      type: s3
  limits:
    global:
      ingestion:
        ingestionBurstSize: 16
        ingestionRate: 8
      retention:
        days: 7
    tenants:
      application:
        retention:
          days: 7
      audit:
        retention:
          days: 1
      infrastructure:
        retention:
          days: 3
  storageClassName: changeme
  tenants:
    mode: openshift-logging
  template:
    compactor:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    distributor:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    gateway:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    indexGateway:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    ingester:
      replicas: 3
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    querier:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    queryFrontend:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
    ruler:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/logging
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/logging
        value: reserved
      nodeSelector:
        node-role.kubernetes.io/logging: ""
