apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-observability
  namespace: openshift-storage
spec:
  additionalConfig:
    bucketclass: noobaa-observ-bucket-class
  generateBucketName: obc-observability-bucket
  storageClassName: openshift-storage.noobaa.io
