apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: "openshift-nmstate"
spec:
  channel: "stable"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "kubernetes-nmstate-operator"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nmstate
  namespace: openshift-nmstate
spec: 
  targetNamespaces: 
    - openshift-nmstate
  upgradeStrategy: Default
---
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
