apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    siteconfig.open-cluster-management.io/sync-wave: "2"
  # ACM Policy'nin dokunmaması için escape ediyoruz:
  name: '{{ "{{" }} .Spec.ClusterName {{ "}}" }}'
  namespace: '{{ "{{" }} .Spec.ClusterName {{ "}}" }}'
spec:
  clusterName: '{{ "{{" }} .Spec.ClusterName {{ "}}" }}'
  clusterNamespace: '{{ "{{" }} .Spec.ClusterName {{ "}}" }}'
  applicationManager:
    enabled: false
  certPolicyController:
    enabled: false
  iamPolicyController:
    enabled: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
