resources:
  - enable-cim.yaml
  - enable-siteconfig.yaml
  - ai-agnostic-node-template-custom
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ai-cluster-templates-klusterletaddon
    namespace: open-cluster-management
    files:
    - KlusterletAddonConfig=KlusterletAddonConfig.yaml
