apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: changeme
  labels:
     machineconfiguration.openshift.io/role: changeme
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: changeme
        mode: 484
        overwrite: true
        path: /etc/NetworkManager/dispatcher.d/increase-rx-tx-ring-buffer
  osImageURL: ""
