apiVersion: metal3.io/v1alpha1

kind: Provisioning

metadata:

  name: provisioning-configuration

spec:

  provisioningNetwork: "Disabled"

  watchAllNamespaces: true
 
apiVersion: agent-install.openshift.io/v1beta1

kind: AgentServiceConfig

metadata:

  name: agent

spec:

  databaseStorage:

    accessModes:

    - ReadWriteOnce

    resources:

      requests:

        storage: 10Gi

  filesystemStorage:

    accessModes:

    - ReadWriteOnce

    resources:

      requests:

        storage: 100Gi

  imageStorage:

    accessModes:

    - ReadWriteOnce

    resources:

      requests:

        storage: 50Gi
 
