kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: quay-enterprise
  annotations:
    openshift.io/node-selector: 'node-role.kubernetes.io/quay='
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-enterprise-og
  namespace: quay-enterprise
spec:
  targetNamespaces:
  - quay-enterprise
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-enterprise 
spec:
  channel: changeme 
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
