apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: hcp-etcd-disks
  namespace: openshift-storage
spec:
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    operator: Equal
    value: "true"
  storage:
    deviceClasses:
    - name: vg1
      fstype: ext4 
      default: true
      nodeSelector:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: Exists
      deviceSelector: 
        paths:
        - /dev/disk/by-path/pci-0000:c3:00.0-scsi-0:0:280:0
        forceWipeDevicesAndDestroyAllData: true
