kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-etcd-backup
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-backup
  labels:
    app: openshift-backup
subjects:
  - kind: ServiceAccount
    name: approver
    namespace: etcdbackup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-etcd-backup
