apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  allowedRegistriesForImport:
    - domainName: quay.io
      insecure: false
    - domainName: registry.redhat.io
      insecure: false
    - domainName: registry.access.redhat.com
      insecure: false
  registrySources:
    allowedRegistries:
    - registry.access.redhat.com
    - quay.io
    - registry.redhat.io
    - image-registry.openshift-image-registry.svc:5000
