apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  files:
  - config.yaml
  behavior: create
generatorOptions:
 disableNameSuffixHash: true

