apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-storage
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    name: odf-operator
    namespace: openshift-storage
    startingCSV: odf-operator.v4.18.1-rhodf
  operatorGroup:
    name: odf-operator
    targetNamespaces: 
      - openshift-storage
  upgradeApproval: None
  versions:
    - odf-operator.v4.18.1-rhodf

