kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: group-sync-operator
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1 
kind: OperatorGroup
metadata:
  name: group-sync-operator-og
  namespace: group-sync-operator
spec:
  targetNamespaces:
  - group-sync-operator
  upgradeStrategy: Default  
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
