apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-local-storage
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    name: local-storage-operator
    namespace: openshift-local-storage
  operatorGroup:
    name: local-storage-operator
    targetNamespaces: 
      - openshift-local-storage
  upgradeApproval: Automatic
