apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-replication
  namespace: openshift-migration
spec:
  generateBucketName: obc-mtc-bucket
  storageClassName: openshift-storage.noobaa.io
