apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - ocs-storagecluster-noobaa-only.yaml
#  - backingstore.yaml
#  - bucketclass.yaml
patches:
  - path: ./odf-sub-patch.yaml
    target:
      kind: Subscription
