apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "example-ai-3node"
  namespace: "example-ai-3node"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.21.6-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEsCJw3L/J5C82Fge6lnHU7kTDXKZy8Z5e6iqoHzvJ7p maydin@maydin-mac"
  clusterName: "example-ai-3node"
  clusterType: HighlyAvailable  
  networkType: "OVNKubernetes"
  # Include references to extraManifest ConfigMaps.
#  extraManifestsRefs:
#    - name: sno-extra-manifest-configmap
  extraLabels:
    ManagedCluster:
      du-profile: "latest"
      sites : "example-multinode"
  machineNetwork:
    - cidr: 192.168.1.0/24
  serviceNetwork:
    - cidr: 100.70.0.0/16
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  apiVIPs:
    - 192.168.1.2
  ingressVIPs:
    - "192.168.1.3"
  additionalNTPSources:
    - 5.5.5.5
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management 
    - name: ai-cluster-templates-KlusterletAddonConfig
      namespace: open-cluster-management
  nodes:
    - automatedCleaningMode: disabled
      bmcAddress: ilo5-virtualmedia+https://1.1.1.1/redfish/v1/Systems/1
      bmcCredentialsName:
        name: example-bmh-secret
      bootMACAddress: b4:7a:f1:ae:9b:67
      bootMode: UEFI
      hostName: master1
      ironicInspect: ""
      nodeNetwork:
        config:
          dns-resolver:
            config:
              search:
                - redhat.com
              server:
                - 10.11.5.160
                - 10.2.70.215
          interfaces:
            - ipv4:
                address:
                  - ip: 192.168.1.10
                    prefix-length: 24
                enabled: true
              ipv6:
                enabled: false
              name: eno2
              state: up
              type: ethernet
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.1.1
                next-hop-interface: eno2
                table-id: 254
        interfaces:
          - macAddress: b4:7a:f1:ae:9b:67
            name: eno2
      role: master
      rootDeviceHints:
        deviceName: /dev/nvme0n1
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
    - automatedCleaningMode: disabled
      bmcAddress: ilo5-virtualmedia+https://2.2.2.2/redfish/v1/Systems/1
      bmcCredentialsName:
        name: example-bmh-secret
      bootMACAddress: b4:7a:f1:a8:73:db
      bootMode: UEFI
      extraAnnotations:
        BareMetalHost:
          bmac.agent-install.openshift.io/remove-agent-and-node-on-delete: "true"
      hostName: master2
      ironicInspect: ""
      nodeNetwork:
        config:
          dns-resolver:
            config:
              search:
                - redhat.com
              server:
                - 10.11.5.160
                - 10.2.70.215
          interfaces:
            - ipv4:
                address:
                  - ip: 192.168.1.11
                    prefix-length: 24
                enabled: true
              ipv6:
                enabled: false
              name: eno2
              state: up
              type: ethernet
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.1.1
                next-hop-interface: eno2
                table-id: 254
        interfaces:
          - macAddress: b4:7a:f1:a8:73:db
            name: eno2
      rootDeviceHints:
        deviceName: /dev/nvme0n1
      role: master
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management

    - automatedCleaningMode: disabled
      bmcAddress: ilo5-virtualmedia+https://3.3.3.3/redfish/v1/Systems/1
      bmcCredentialsName:
        name: example-bmh-secret
      bootMACAddress: b4:7a:f1:a8:73:dc
      bootMode: UEFI
      extraAnnotations:
        BareMetalHost:
          bmac.agent-install.openshift.io/remove-agent-and-node-on-delete: "true"
      hostName: master3
      ironicInspect: ""
      nodeNetwork:
        config:
          dns-resolver:
            config:
              search:
                - redhat.com
              server:
                - 10.11.5.160
                - 10.2.70.215
          interfaces:
            - ipv4:
                address:
                  - ip: 192.168.1.12
                    prefix-length: 24
                enabled: true
              ipv6:
                enabled: false
              name: eno2
              state: up
              type: ethernet
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.1.1
                next-hop-interface: eno2
                table-id: 254
        interfaces:
          - macAddress: b4:7a:f1:a8:73:dc
            name: eno2
      rootDeviceHints:
        deviceName: /dev/nvme0n1
      role: master
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
