apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ./lv-discovery-patch.yaml
    target:
      kind: LocalVolumeDiscovery
  - path: ./lvs-patch.yaml
    target:
      kind: LocalVolumeSet
