apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nodehealthcheck-sample
  resourceVersion: "7304977"
spec:
  minHealthy: 51%
  remediationTemplate:
    apiVersion: self-node-remediation.medik8s.io/v1alpha1
    kind: SelfNodeRemediationTemplate
    name: self-node-remediation-automatic-strategy-template
    namespace: openshift-workload-availability
  selector:
    matchExpressions:
    - key: node-role.kubernetes.io/hp
      operator: Exists
  unhealthyConditions:
  - duration: 300s
    status: "False"
    type: Ready
  - duration: 300s
    status: Unknown
    type: Ready
