apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: fence-agents-remediation-operator 
spec:
  remediationAction: enforce
  severity: medium
  complianceType: musthave
  subscription:
    name: fence-agents-remediation
    namespace: openshift-workload-availability
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable
  upgradeApproval: Automatic
