apiVersion: v1
kind: Secret
metadata:
  name: image-registry-private-configuration-user 
  namespace: openshift-image-registry
type: Opaque
data:
  REGISTRY_STORAGE_S3_ACCESSKEY: '{{ fromSecret "openshift-storage" "obc-internalreg" "AWS_ACCESS_KEY_ID" }}'
  REGISTRY_STORAGE_S3_SECRETKEY: '{{ fromSecret "openshift-storage" "obc-internalreg" "AWS_SECRET_ACCESS_KEY" }}'
