infraEnabled: false
externalRouterEnabled: false
replicas: 3

# Exposing variables that were hardcoded in your raw definition
http2Enabled: "true"
defaultCertificateName: tls-secret
forwardedHeaderPolicy: Append
minTLSVersion: VersionTLS12

ciphers:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384
  - AES128-GCM-SHA256
  - AES128-SHA
  - AES128-SHA256
  - AES256-GCM-SHA384
  - AES256-SHA
  - AES256-SHA256
  - CAMELLIA128-SHA
  - CAMELLIA256-SHA
