apiVersion: v1
kind: ConfigMap
metadata:
  name: hcp-chronyd
  namespace: clusters
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
        name: 99-worker-chrony-conf-override
    spec:
      config:
        ignition:
          version: 3.5.0
        storage:
          files:
            - contents:
                source: data:text/plain;charset=utf-8;base64,TODO
              mode: 420
              overwrite: true
              path: /etc/chrony.conf
