apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ./chronyd-patch-worker.yaml
    target:
      name: 50-workers-chrony-configuration
      kind: MachineConfig  
  - path: ./chronyd-patch-master.yaml
    target:
      name: 50-masters-chrony-configuration
      kind: MachineConfig  
