apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:

   - name: rsyslog-qradar 
     type: syslog 
     syslog: 
       rfc: RFC5424
       severity: debug
     url: changeme
  pipelines:
   - name: audit-qradar 
     inputRefs: 
     - audit
     outputRefs: 
     - rsyslog-qradar 
     labels:
       syslog: changeme
   - name: app-qradar
     inputRefs: 
     - application
     outputRefs: 
     - default
     - rsyslog-qradar
     labels:
       syslog: changeme
   - name: infra
     inputRefs:
     - infrastructure
     outputRefs:
     - default

