apiVersion: "observability.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: forward
  namespace: openshift-logging
spec:
  collector:
    nodeSelector:
      kubernetes.io/os: linux
    resources: {}
  serviceAccount:
    name: collector
  outputs:
    - lokiStack:
        authentication:
          token:
            from: serviceAccount
        target:
          name: logging-loki
          namespace: openshift-logging
      name: default-lokistack
      tls:
        ca:
          configMapName: openshift-service-ca.crt
          key: service-ca.crt
      type: lokiStack
  pipelines:
    - inputRefs:
        - audit
      name: default-before
      outputRefs:
        - default-lokistack
